# Generated by Django 4.2.7 on 2023-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('github', models.URLField()),
                ('linkdin', models.URLField()),
                ('gmail', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
